# Generated by Django 5.1.4 on 2024-12-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_art', models.AutoField(primary_key=True, serialize=False)),
                ('date_art', models.DateField(blank=True, null=True)),
                ('title_art', models.CharField(max_length=128)),
                ('hook_art', models.TextField(blank=True, null=True)),
                ('image_art', models.CharField(blank=True, max_length=64, null=True)),
                ('content_art', models.TextField()),
            ],
            options={
                'db_table': 't_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('name_cat', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 't_category',
                'managed': False,
            },
        ),
    ]
